export type ProjectType = "saas" | "personal" | "school";
export type ProjectStatus = "finished" | "inprogress" | "aborted";

export interface Project {
  id: string;
  title: string;
  type?: ProjectType;
  year?: string;
  status?: ProjectStatus;
  links?: string[];
  technologies: string[];
  image_count: number;
  length?: string | { fr: string; en: string };
  preview?: string;
}

export const PROJECTS: Project[] = [
    {
    id: "framly",
    title: "Framly",
    type: "saas",
    year: "2026",
    status: "inprogress",
    technologies: ["Next.js", "Fastify", "Supabase", "OpenAI", "FAL AI", "xAI", "FFmpeg", "Bull/Redis"],
    image_count: 4,
  },
  {
    id: "deviscope",
    title: "Deviscope",
    type: "saas",
    year: "2026",
    status: "finished",
    links: ["https://github.com/pierre50/deviscope"],
    technologies: ["Next.js", "Fastify", "Supabase", "OpenAI", "Bull/Redis"],
    image_count: 3,
  },
  {
    id: "rts",
    title: "RTS game",
    type: "personal",
    year: "2020",
    status: "inprogress",
    preview: "https://pierre50.github.io/RTS-game/",
    links: [
      "https://github.com/pierre50/RTS-game",
      "https://pierre50.github.io/RTS-game/",
    ],
    technologies: ["PixiJS"],
    image_count: 1,
  },
  {
    id: "kiki",
    title: "Kiki",
    type: "personal",
    year: "2022",
    status: "aborted",
    links: ["https://github.com/pierre50/kiki"],
    technologies: ["BabylonJS"],
    image_count: 1,
  },
  {
    id: "supfile",
    title: "Supfile",
    type: "school",
    year: "2018",
    length: { fr: "6 mois", en: "6 months" },
    status: "finished",
    links: [
      "https://github.com/pierre50/upload-frontend",
      "https://github.com/pierre50/upload-backend",
    ],
    technologies: ["VueJS", "ElementUI", "Laravel"],
    image_count: 5,
  },
  {
    id: "awale",
    title: "Awale",
    type: "school",
    year: "2018",
    length: { fr: "2 semaines", en: "2 weeks" },
    status: "finished",
    links: ["https://github.com/pierre50/awale"],
    technologies: ["VueJS", "ElementUi"],
    image_count: 3,
  },
  {
    id: "battleship",
    title: "NodeJS Battleship",
    type: "school",
    year: "2018",
    length: { fr: "2 semaines", en: "2 weeks" },
    status: "finished",
    links: ["https://github.com/pierre50/Battleship"],
    technologies: [
      "NodeJS",
      "HTML",
      "jQuery",
      "Javascript",
      "Bootstrap",
      "SocketIO",
    ],
    image_count: 3,
  },
  {
    id: "weathermap",
    title: "UWP WeatherMap",
    type: "school",
    year: "2017",
    length: { fr: "1 semaines", en: "1 weeks" },
    status: "finished",
    technologies: [
      "C#",
      "Universal Windows App",
      "GoogleMap API",
      "OpenWeatherMap API",
    ],
    image_count: 3,
  },
  {
    id: "biblio",
    title: "Angular Biblio",
    type: "personal",
    year: "2017",
    length: { fr: "1 semaines", en: "1 weeks" },
    status: "finished",
    technologies: [
      "Angular2",
      "HTML",
      "Bootstrap",
      "Javascript",
      "jsPDF",
      "Php",
    ],
    image_count: 2,
  },
  {
    id: "supinfy",
    title: "Asp.net Streaming Music",
    type: "school",
    year: "2017",
    length: { fr: "2 semaines", en: "2 weeks" },
    status: "finished",
    technologies: [
      "Asp.net",
      "C#",
      "Jamendo API",
      "Javascript",
      "jQuery",
      "Bootstrap",
    ],
    image_count: 3,
  },
  {
    id: "qwirk",
    title: "NodeJS Chat App",
    type: "school",
    year: "2017",
    length: { fr: "6 mois", en: "6 months" },
    status: "finished",
    links: ["https://github.com/pierre50/qwirk"],
    technologies: [
      "NodeJS",
      "Javascript",
      "jQuery",
      "Bootstrap",
      "HTML",
      "WebRTC",
      "SocketIO",
    ],
    image_count: 3,
  },
  {
    id: "imap",
    title: "Swift Map",
    type: "school",
    year: "2016",
    length: { fr: "2 semaines", en: "2 weeks" },
    status: "finished",
    technologies: ["iOS", "Qwirk", "Core Data"],
    image_count: 3,
  },
  {
    id: "supsale",
    title: "Servlet Ad Website",
    type: "school",
    year: "2016",
    length: { fr: "1 mois", en: "1 months" },
    status: "finished",
    technologies: ["Java", "Servlet", "Javascript", "jQuery", "Bootstrap"],
    image_count: 6,
  },
  {
    id: "symfony",
    title: "Symfony Store Website",
    type: "personal",
    year: "2016",
    length: { fr: "2 semaines", en: "2 weeks" },
    status: "finished",
    technologies: [
      "Symfony",
      "PHP",
      "HTML",
      "Bootstrap",
      "jQuery",
      "Javascript",
    ],
    image_count: 6,
  },
  {
    id: "cakeblog",
    title: "Cakephp Blog Website",
    type: "personal",
    year: "2015",
    length: { fr: "2 semaines", en: "2 weeks" },
    status: "finished",
    technologies: ["CakePhp", "PHP", "HTML", "Bootstrap"],
    image_count: 2,
  },
  {
    id: "freefallin",
    title: "Android 2D Game",
    type: "personal",
    year: "2015",
    length: { fr: "4 mois", en: "4 months" },
    status: "aborted",
    technologies: ["GML", "Google Game API", "Facebook API"],
    image_count: 4,
  },
  {
    id: "easyhome",
    title: "Php Annonces immo",
    type: "school",
    year: "2015",
    length: { fr: "3 mois", en: "3 months" },
    status: "finished",
    technologies: ["PHP", "HTML", "Bootstrap"],
    image_count: 1,
  },
];
